use std::collections::HashMap;
use std::sync::LazyLock;

use serde::{Deserialize, Serialize};

use crate::messages::types::{Api, Provider, Usage, UsageCost};
use crate::models::cost::calculate_cost;

// ─── Input types ──────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum InputType {
    Text,
    Image,
}

// ─── Model cost (per-million token rates in USD) ──────────────────────────────

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct ModelCost {
    pub input: f64,
    pub output: f64,
    pub cache_read: f64,
    pub cache_write: f64,
}

// ─── Model definition ─────────────────────────────────────────────────────────

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Model {
    pub id: String,
    pub name: String,
    pub api: Api,
    pub provider: Provider,
    pub base_url: String,
    pub reasoning: bool,
    pub input_types: Vec<InputType>,
    pub cost: ModelCost,
    pub context_window: u64,
    pub max_tokens: u64,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub headers: Option<HashMap<String, String>>,
}

impl Model {
    pub fn calculate_cost(&self, usage: &Usage) -> UsageCost {
        calculate_cost(&self.cost, usage)
    }

    /// Annotate a `Usage` with cost information.
    pub fn annotate_usage(&self, mut usage: Usage) -> Usage {
        usage.cost = self.calculate_cost(&usage);
        usage
    }

    pub fn supports_images(&self) -> bool {
        self.input_types.contains(&InputType::Image)
    }

    pub fn supports_reasoning(&self) -> bool {
        self.reasoning
    }
}

// ─── Built-in model catalogue ─────────────────────────────────────────────────

/// Lazily-initialised, process-lifetime catalogue of built-in models.
///
/// Contains the 101 most commonly used models across all supported providers.
/// pi-mono auto-generates 200+ entries; additional models can be added here
/// or registered at runtime via `ModelRegistry::register`.
///
/// Allocated once on first access; all subsequent calls return a reference to
/// the same slice.
static BUILT_IN_MODELS: LazyLock<Vec<Model>> = LazyLock::new(|| {
    vec![
        // ── Anthropic ──────────────────────────────────────────────────────
        Model {
            id: "claude-opus-4-5".to_string(),
            name: "Claude Opus 4.5".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 15.0,
                output: 75.0,
                cache_read: 1.5,
                cache_write: 18.75,
            },
            context_window: 200_000,
            max_tokens: 32_000,
            headers: None,
        },
        Model {
            id: "claude-sonnet-4-5".to_string(),
            name: "Claude Sonnet 4.5".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 16_000,
            headers: None,
        },
        Model {
            id: "claude-haiku-3-5".to_string(),
            name: "Claude Haiku 3.5".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.8,
                output: 4.0,
                cache_read: 0.08,
                cache_write: 1.0,
            },
            context_window: 200_000,
            max_tokens: 8_096,
            headers: None,
        },
        Model {
            id: "claude-opus-4-6".to_string(),
            name: "Claude Opus 4.6".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 15.0,
                output: 75.0,
                cache_read: 1.5,
                cache_write: 18.75,
            },
            context_window: 200_000,
            max_tokens: 32_000,
            headers: None,
        },
        Model {
            id: "claude-sonnet-4-6".to_string(),
            name: "Claude Sonnet 4.6".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 16_000,
            headers: None,
        },
        // ── OpenAI ────────────────────────────────────────────────────────
        Model {
            id: "gpt-4o".to_string(),
            name: "GPT-4o".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 2.5,
                output: 10.0,
                cache_read: 1.25,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            headers: None,
        },
        Model {
            id: "gpt-4o-mini".to_string(),
            name: "GPT-4o mini".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.15,
                output: 0.6,
                cache_read: 0.075,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            headers: None,
        },
        Model {
            id: "gpt-4.1".to_string(),
            name: "GPT-4.1".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 2.0,
                output: 8.0,
                cache_read: 0.5,
                cache_write: 0.0,
            },
            context_window: 1_047_576,
            max_tokens: 32_768,
            headers: None,
        },
        Model {
            id: "gpt-4.1-mini".to_string(),
            name: "GPT-4.1 mini".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.4,
                output: 1.6,
                cache_read: 0.1,
                cache_write: 0.0,
            },
            context_window: 1_047_576,
            max_tokens: 32_768,
            headers: None,
        },
        Model {
            id: "o3".to_string(),
            name: "OpenAI o3".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 10.0,
                output: 40.0,
                cache_read: 2.5,
                cache_write: 0.0,
            },
            context_window: 200_000,
            max_tokens: 100_000,
            headers: None,
        },
        Model {
            id: "o4-mini".to_string(),
            name: "OpenAI o4-mini".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 1.1,
                output: 4.4,
                cache_read: 0.275,
                cache_write: 0.0,
            },
            context_window: 200_000,
            max_tokens: 100_000,
            headers: None,
        },
        // ── Google ────────────────────────────────────────────────────────
        Model {
            id: "gemini-2.5-pro-preview-05-06".to_string(),
            name: "Gemini 2.5 Pro".to_string(),
            api: Api::GoogleGenerativeAI,
            provider: Provider::Google,
            base_url: "https://generativelanguage.googleapis.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 1.25,
                output: 10.0,
                cache_read: 0.31,
                cache_write: 0.0,
            },
            context_window: 1_000_000,
            max_tokens: 65_536,
            headers: None,
        },
        Model {
            id: "gemini-2.5-flash-preview-05-20".to_string(),
            name: "Gemini 2.5 Flash".to_string(),
            api: Api::GoogleGenerativeAI,
            provider: Provider::Google,
            base_url: "https://generativelanguage.googleapis.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.15,
                output: 0.6,
                cache_read: 0.0375,
                cache_write: 0.0,
            },
            context_window: 1_000_000,
            max_tokens: 65_536,
            headers: None,
        },
        Model {
            id: "gemini-2.0-flash".to_string(),
            name: "Gemini 2.0 Flash".to_string(),
            api: Api::GoogleGenerativeAI,
            provider: Provider::Google,
            base_url: "https://generativelanguage.googleapis.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.1,
                output: 0.4,
                cache_read: 0.025,
                cache_write: 0.0,
            },
            context_window: 1_000_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Groq ──────────────────────────────────────────────────────────
        Model {
            id: "llama-3.3-70b-versatile".to_string(),
            name: "Llama 3.3 70B Versatile (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.59,
                output: 0.79,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 32_768,
            headers: None,
        },
        Model {
            id: "moonshotai/kimi-k2-instruct".to_string(),
            name: "Kimi K2 (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 1.0,
                output: 3.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 16_384,
            headers: None,
        },
        // ── xAI ───────────────────────────────────────────────────────────
        Model {
            id: "grok-3".to_string(),
            name: "Grok 3".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::XAI,
            base_url: "https://api.x.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 16_384,
            headers: None,
        },
        Model {
            id: "grok-3-mini".to_string(),
            name: "Grok 3 Mini".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::XAI,
            base_url: "https://api.x.ai".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.3,
                output: 0.5,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 16_384,
            headers: None,
        },
        // ── Mistral ───────────────────────────────────────────────────────
        Model {
            id: "mistral-large-latest".to_string(),
            name: "Mistral Large".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Mistral,
            base_url: "https://api.mistral.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 2.0,
                output: 6.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── OpenRouter ────────────────────────────────────────────────────
        Model {
            id: "meta-llama/llama-4-maverick".to_string(),
            name: "Llama 4 Maverick (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.18,
                output: 0.6,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 524_288,
            max_tokens: 16_384,
            headers: Some({
                let mut h = HashMap::new();
                h.insert(
                    "HTTP-Referer".to_string(),
                    "https://github.com/pi-mono-rs".to_string(),
                );
                h
            }),
        },
        // ── Cerebras ──────────────────────────────────────────────────────
        Model {
            id: "llama-4-scout-17b-16e-instruct".to_string(),
            name: "Llama 4 Scout (Cerebras)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Cerebras,
            base_url: "https://api.cerebras.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.1,
                output: 0.1,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Additional OpenAI Models ─────────────────────────────────────────
        Model {
            id: "gpt-4o-2024-11-20".to_string(),
            name: "GPT-4o (Nov 2024)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 2.5,
                output: 10.0,
                cache_read: 1.25,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            headers: None,
        },
        Model {
            id: "gpt-4o-mini-2024-07-18".to_string(),
            name: "GPT-4o mini (Jul 2024)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.15,
                output: 0.6,
                cache_read: 0.075,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            headers: None,
        },
        Model {
            id: "o1-preview".to_string(),
            name: "OpenAI o1-preview".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 15.0,
                output: 60.0,
                cache_read: 7.5,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 32_768,
            headers: None,
        },
        Model {
            id: "o1-mini".to_string(),
            name: "OpenAI o1-mini".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 1.1,
                output: 4.4,
                cache_read: 0.55,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 65_536,
            headers: None,
        },
        // ── Additional Anthropic Models ──────────────────────────────────────
        Model {
            id: "claude-3-7-sonnet-20250219".to_string(),
            name: "Claude 3.7 Sonnet".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 128_000,
            headers: None,
        },
        Model {
            id: "claude-3-5-sonnet-20241022".to_string(),
            name: "Claude 3.5 Sonnet (Oct 2024)".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "claude-3-5-haiku-20241022".to_string(),
            name: "Claude 3.5 Haiku".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.8,
                output: 4.0,
                cache_read: 0.08,
                cache_write: 1.0,
            },
            context_window: 200_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "claude-3-opus-20240229".to_string(),
            name: "Claude 3 Opus".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 15.0,
                output: 75.0,
                cache_read: 1.5,
                cache_write: 18.75,
            },
            context_window: 200_000,
            max_tokens: 4_096,
            headers: None,
        },
        Model {
            id: "claude-3-sonnet-20240229".to_string(),
            name: "Claude 3 Sonnet".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 4_096,
            headers: None,
        },
        Model {
            id: "claude-3-haiku-20240307".to_string(),
            name: "Claude 3 Haiku".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.25,
                output: 1.25,
                cache_read: 0.03,
                cache_write: 0.31,
            },
            context_window: 200_000,
            max_tokens: 4_096,
            headers: None,
        },
        // ── Additional Google Models ─────────────────────────────────────────
        Model {
            id: "gemini-2.0-flash-lite".to_string(),
            name: "Gemini 2.0 Flash Lite".to_string(),
            api: Api::GoogleGenerativeAI,
            provider: Provider::Google,
            base_url: "https://generativelanguage.googleapis.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.075,
                output: 0.3,
                cache_read: 0.01875,
                cache_write: 0.0,
            },
            context_window: 1_000_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "gemini-1.5-pro".to_string(),
            name: "Gemini 1.5 Pro".to_string(),
            api: Api::GoogleGenerativeAI,
            provider: Provider::Google,
            base_url: "https://generativelanguage.googleapis.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 1.25,
                output: 5.0,
                cache_read: 0.31,
                cache_write: 0.0,
            },
            context_window: 2_000_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "gemini-1.5-flash".to_string(),
            name: "Gemini 1.5 Flash".to_string(),
            api: Api::GoogleGenerativeAI,
            provider: Provider::Google,
            base_url: "https://generativelanguage.googleapis.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.075,
                output: 0.3,
                cache_read: 0.01875,
                cache_write: 0.0,
            },
            context_window: 1_000_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Additional Mistral Models ────────────────────────────────────────
        Model {
            id: "mistral-large-2407".to_string(),
            name: "Mistral Large (24.07)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Mistral,
            base_url: "https://api.mistral.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 2.0,
                output: 6.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "mistral-medium".to_string(),
            name: "Mistral Medium".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Mistral,
            base_url: "https://api.mistral.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 2.7,
                output: 8.1,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "mistral-small".to_string(),
            name: "Mistral Small".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Mistral,
            base_url: "https://api.mistral.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 1.0,
                output: 3.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "codestral".to_string(),
            name: "Codestral".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Mistral,
            base_url: "https://api.mistral.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.2,
                output: 0.6,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Additional Groq Models ───────────────────────────────────────────
        Model {
            id: "llama-3.1-8b-instant".to_string(),
            name: "Llama 3.1 8B Instant (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.05,
                output: 0.08,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "llama-3.1-70b-versatile".to_string(),
            name: "Llama 3.1 70B Versatile (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.59,
                output: 0.79,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "llama3-8b-8192".to_string(),
            name: "Llama 3 8B (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.05,
                output: 0.08,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_192,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "llama3-70b-8192".to_string(),
            name: "Llama 3 70B (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.59,
                output: 0.79,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_192,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "mixtral-8x7b-32768".to_string(),
            name: "Mixtral 8x7B (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.24,
                output: 0.24,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_768,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "gemma-7b-it".to_string(),
            name: "Gemma 7B IT (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.07,
                output: 0.07,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_192,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "gemma2-9b-it".to_string(),
            name: "Gemma 2 9B IT (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.20,
                output: 0.20,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_192,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Additional xAI Models ────────────────────────────────────────────
        Model {
            id: "grok-2".to_string(),
            name: "Grok 2".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::XAI,
            base_url: "https://api.x.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 2.0,
                output: 10.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "grok-2-vision".to_string(),
            name: "Grok 2 Vision".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::XAI,
            base_url: "https://api.x.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 2.0,
                output: 10.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_768,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Additional OpenRouter Models ─────────────────────────────────────
        Model {
            id: "openai/gpt-4o".to_string(),
            name: "GPT-4o (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 5.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "anthropic/claude-3.5-sonnet".to_string(),
            name: "Claude 3.5 Sonnet (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 200_000,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "google/gemini-2.5-pro".to_string(),
            name: "Gemini 2.5 Pro (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 1.25,
                output: 10.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 1_000_000,
            max_tokens: 65_536,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "deepseek/deepseek-chat".to_string(),
            name: "DeepSeek V3 (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.07,
                output: 0.28,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 64_000,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "deepseek/deepseek-r1".to_string(),
            name: "DeepSeek R1 (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.55,
                output: 2.19,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 64_000,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        // ── Additional Cerebras Models ───────────────────────────────────────
        Model {
            id: "llama-3.3-70b".to_string(),
            name: "Llama 3.3 70B (Cerebras)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Cerebras,
            base_url: "https://api.cerebras.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.85,
                output: 1.2,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "llama-3.1-8b".to_string(),
            name: "Llama 3.1 8B (Cerebras)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Cerebras,
            base_url: "https://api.cerebras.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.10,
                output: 0.10,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Azure OpenAI Models ──────────────────────────────────────────────
        Model {
            id: "gpt-4o".to_string(),
            name: "GPT-4o (Azure)".to_string(),
            api: Api::AzureOpenAIResponses,
            provider: Provider::AzureOpenAI,
            base_url: "https://api.openai.azure.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 2.5,
                output: 10.0,
                cache_read: 1.25,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            headers: None,
        },
        Model {
            id: "gpt-4o-mini".to_string(),
            name: "GPT-4o mini (Azure)".to_string(),
            api: Api::AzureOpenAIResponses,
            provider: Provider::AzureOpenAI,
            base_url: "https://api.openai.azure.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.15,
                output: 0.6,
                cache_read: 0.075,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 16_384,
            headers: None,
        },
        // ── AWS Bedrock Models ───────────────────────────────────────────────
        Model {
            id: "anthropic.claude-3-5-sonnet-20241022-v2:0".to_string(),
            name: "Claude 3.5 Sonnet (Bedrock)".to_string(),
            api: Api::BedrockConverseStream,
            provider: Provider::AmazonBedrock,
            base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "anthropic.claude-3-5-haiku-20241022-v1:0".to_string(),
            name: "Claude 3.5 Haiku (Bedrock)".to_string(),
            api: Api::BedrockConverseStream,
            provider: Provider::AmazonBedrock,
            base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.8,
                output: 4.0,
                cache_read: 0.08,
                cache_write: 1.0,
            },
            context_window: 200_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "amazon.nova-pro-v1:0".to_string(),
            name: "Nova Pro (Bedrock)".to_string(),
            api: Api::BedrockConverseStream,
            provider: Provider::AmazonBedrock,
            base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.8,
                output: 3.2,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 300_000,
            max_tokens: 5_120,
            headers: None,
        },
        Model {
            id: "amazon.nova-lite-v1:0".to_string(),
            name: "Nova Lite (Bedrock)".to_string(),
            api: Api::BedrockConverseStream,
            provider: Provider::AmazonBedrock,
            base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.06,
                output: 0.24,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 300_000,
            max_tokens: 5_120,
            headers: None,
        },
        Model {
            id: "meta.llama3-3-70b-instruct-v1:0".to_string(),
            name: "Llama 3.3 70B (Bedrock)".to_string(),
            api: Api::BedrockConverseStream,
            provider: Provider::AmazonBedrock,
            base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.72,
                output: 0.72,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "meta.llama3-1-405b-instruct-v1:0".to_string(),
            name: "Llama 3.1 405B (Bedrock)".to_string(),
            api: Api::BedrockConverseStream,
            provider: Provider::AmazonBedrock,
            base_url: "https://bedrock-runtime.us-east-1.amazonaws.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 2.4,
                output: 2.4,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Google Vertex AI Models ──────────────────────────────────────────
        Model {
            id: "gemini-2.5-pro-preview-03-25".to_string(),
            name: "Gemini 2.5 Pro (Vertex)".to_string(),
            api: Api::GoogleVertex,
            provider: Provider::GoogleVertex,
            base_url: "https://us-central1-aiplatform.googleapis.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 1.25,
                output: 10.0,
                cache_read: 0.31,
                cache_write: 0.0,
            },
            context_window: 1_000_000,
            max_tokens: 65_536,
            headers: None,
        },
        Model {
            id: "gemini-1.5-pro-002".to_string(),
            name: "Gemini 1.5 Pro 002 (Vertex)".to_string(),
            api: Api::GoogleVertex,
            provider: Provider::GoogleVertex,
            base_url: "https://us-central1-aiplatform.googleapis.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 1.25,
                output: 5.0,
                cache_read: 0.31,
                cache_write: 0.0,
            },
            context_window: 2_000_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "claude-3-5-sonnet-v2@20241022".to_string(),
            name: "Claude 3.5 Sonnet (Vertex)".to_string(),
            api: Api::GoogleVertex,
            provider: Provider::GoogleVertex,
            base_url: "https://us-central1-aiplatform.googleapis.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── MiniMax Models ───────────────────────────────────────────────────
        Model {
            id: "abab6.5s".to_string(),
            name: "MiniMax abab6.5s".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::MiniMax,
            base_url: "https://api.minimax.chat".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.1,
                output: 0.1,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "abab6.5-chat".to_string(),
            name: "MiniMax abab6.5 Chat".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::MiniMax,
            base_url: "https://api.minimax.chat".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.2,
                output: 0.2,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── HuggingFace Models ───────────────────────────────────────────────
        Model {
            id: "meta-llama/Meta-Llama-3.1-70B-Instruct".to_string(),
            name: "Llama 3.1 70B (HF Inference)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::HuggingFace,
            base_url: "https://api-inference.huggingface.co".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.0,
                output: 0.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "mistralai/Mistral-7B-Instruct-v0.3".to_string(),
            name: "Mistral 7B (HF Inference)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::HuggingFace,
            base_url: "https://api-inference.huggingface.co".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.0,
                output: 0.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── More OpenRouter Models ───────────────────────────────────────────
        Model {
            id: "meta-llama/llama-4-scout".to_string(),
            name: "Llama 4 Scout (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.5,
                output: 0.5,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "qwen/qwen-2.5-72b-instruct".to_string(),
            name: "Qwen 2.5 72B Instruct (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.35,
                output: 0.4,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "microsoft/phi-4".to_string(),
            name: "Phi 4 (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.07,
                output: 0.14,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 16_000,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "01-ai/yi-34b-chat".to_string(),
            name: "Yi 34B Chat (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.8,
                output: 0.8,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_000,
            max_tokens: 4_096,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "perplexity/sonar".to_string(),
            name: "Perplexity Sonar (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 1.0,
                output: 1.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "cohere/command-r-plus".to_string(),
            name: "Command R+ (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 4_096,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "nousresearch/hermes-3-llama-3.1-405b".to_string(),
            name: "Hermes 3 Llama 3.1 405B (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 1.5,
                output: 1.5,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "x-ai/grok-3-beta".to_string(),
            name: "Grok 3 Beta (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        Model {
            id: "nvidia/llama-3.1-nemotron-70b-instruct".to_string(),
            name: "Llama 3.1 Nemotron 70B (OpenRouter)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenRouter,
            base_url: "https://openrouter.ai/api".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.35,
                output: 0.4,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 8_192,
            headers: Some({
                let mut h = std::collections::HashMap::new();
                h.insert("HTTP-Referer".to_string(), "https://github.com/pi-mono-rs".to_string());
                h
            }),
        },
        // ── Alibaba Models ───────────────────────────────────────────────────
        Model {
            id: "qwen-turbo".to_string(),
            name: "Qwen Turbo".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("alibaba".to_string()),
            base_url: "https://dashscope.aliyuncs.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.5,
                output: 1.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "qwen-plus".to_string(),
            name: "Qwen Plus".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("alibaba".to_string()),
            base_url: "https://dashscope.aliyuncs.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 1.0,
                output: 2.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "qwen-max".to_string(),
            name: "Qwen Max".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("alibaba".to_string()),
            base_url: "https://dashscope.aliyuncs.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 2.4,
                output: 9.6,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 32_768,
            max_tokens: 8_192,
            headers: None,
        },
        // ── AI21 Models ──────────────────────────────────────────────────────
        Model {
            id: "jamba-1.5-large".to_string(),
            name: "Jamba 1.5 Large".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("ai21".to_string()),
            base_url: "https://api.ai21.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 2.0,
                output: 8.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 256_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "jamba-1.5-mini".to_string(),
            name: "Jamba 1.5 Mini".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("ai21".to_string()),
            base_url: "https://api.ai21.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.2,
                output: 0.4,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 256_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Cohere Models ────────────────────────────────────────────────────
        Model {
            id: "command-r".to_string(),
            name: "Command R".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("cohere".to_string()),
            base_url: "https://api.cohere.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.15,
                output: 0.6,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 4_096,
            headers: None,
        },
        Model {
            id: "command-r-plus".to_string(),
            name: "Command R Plus".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("cohere".to_string()),
            base_url: "https://api.cohere.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 4_096,
            headers: None,
        },
        // ── Perplexity Models ────────────────────────────────────────────────
        Model {
            id: "sonar".to_string(),
            name: "Sonar".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("perplexity".to_string()),
            base_url: "https://api.perplexity.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 1.0,
                output: 1.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "sonar-pro".to_string(),
            name: "Sonar Pro".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("perplexity".to_string()),
            base_url: "https://api.perplexity.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 200_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "sonar-reasoning".to_string(),
            name: "Sonar Reasoning".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Custom("perplexity".to_string()),
            base_url: "https://api.perplexity.ai".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 2.0,
                output: 8.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        // ── Additional Models ────────────────────────────────────────────────
        Model {
            id: "o3-mini".to_string(),
            name: "OpenAI o3-mini".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 1.1,
                output: 4.4,
                cache_read: 0.55,
                cache_write: 0.0,
            },
            context_window: 200_000,
            max_tokens: 100_000,
            headers: None,
        },
        Model {
            id: "gpt-4-turbo".to_string(),
            name: "GPT-4 Turbo".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 10.0,
                output: 30.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 4_096,
            headers: None,
        },
        Model {
            id: "gpt-4".to_string(),
            name: "GPT-4".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 30.0,
                output: 60.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_192,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "gpt-3.5-turbo".to_string(),
            name: "GPT-3.5 Turbo".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::OpenAI,
            base_url: "https://api.openai.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.5,
                output: 1.5,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 16_384,
            max_tokens: 4_096,
            headers: None,
        },
        Model {
            id: "claude-3-opus-latest".to_string(),
            name: "Claude 3 Opus Latest".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: true,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 15.0,
                output: 75.0,
                cache_read: 1.5,
                cache_write: 18.75,
            },
            context_window: 200_000,
            max_tokens: 4_096,
            headers: None,
        },
        Model {
            id: "claude-3-sonnet-latest".to_string(),
            name: "Claude 3 Sonnet Latest".to_string(),
            api: Api::AnthropicMessages,
            provider: Provider::Anthropic,
            base_url: "https://api.anthropic.com".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 3.0,
                output: 15.0,
                cache_read: 0.3,
                cache_write: 3.75,
            },
            context_window: 200_000,
            max_tokens: 4_096,
            headers: None,
        },
        Model {
            id: "llama-3.2-1b-preview".to_string(),
            name: "Llama 3.2 1B (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.04,
                output: 0.04,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "llama-3.2-3b-preview".to_string(),
            name: "Llama 3.2 3B (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.06,
                output: 0.06,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "llama-3.2-11b-vision-preview".to_string(),
            name: "Llama 3.2 11B Vision (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.18,
                output: 0.18,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "llama-3.2-90b-vision-preview".to_string(),
            name: "Llama 3.2 90B Vision (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text, InputType::Image],
            cost: ModelCost {
                input: 0.90,
                output: 0.90,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 128_000,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "mixtral-8x22b-instruct".to_string(),
            name: "Mixtral 8x22B Instruct (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.90,
                output: 0.90,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 65_536,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "gemma2-2b-it".to_string(),
            name: "Gemma 2 2B IT (Groq)".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::Groq,
            base_url: "https://api.groq.com/openai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 0.10,
                output: 0.10,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 8_192,
            max_tokens: 8_192,
            headers: None,
        },
        Model {
            id: "grok-beta".to_string(),
            name: "Grok Beta".to_string(),
            api: Api::OpenAICompletions,
            provider: Provider::XAI,
            base_url: "https://api.x.ai".to_string(),
            reasoning: false,
            input_types: vec![InputType::Text],
            cost: ModelCost {
                input: 5.0,
                output: 15.0,
                cache_read: 0.0,
                cache_write: 0.0,
            },
            context_window: 131_072,
            max_tokens: 8_192,
            headers: None,
        },
    ]
});

/// Returns the built-in model catalogue as a static slice.
///
/// The catalogue is allocated exactly once (on first call) and shared for
/// the lifetime of the process.  Pricing is in USD per million tokens and is
/// sourced from public provider pricing pages (as of 2025-Q2).  Always
/// verify against the provider's current pricing for billing-critical
/// applications.
pub fn built_in_models() -> &'static [Model] {
    &BUILT_IN_MODELS
}

/// Look up a built-in model by its ID.
pub fn find_model(id: &str) -> Option<Model> {
    built_in_models().iter().find(|m| m.id == id).cloned()
}

/// Returns all built-in models for a given provider.
pub fn models_for_provider(provider: &Provider) -> Vec<Model> {
    built_in_models()
        .iter()
        .filter(|m| &m.provider == provider)
        .cloned()
        .collect()
}

/// Returns all built-in models that use a given API type.
pub fn models_for_api(api: &Api) -> Vec<Model> {
    built_in_models()
        .iter()
        .filter(|m| &m.api == api)
        .cloned()
        .collect()
}
